### ISSUE TITLE
Error: spawn gulp ENOENT

### ISSUE THREAD

**Issue by Shaman05** [Qquanwei/electron-windows-inno-installer#1]
操作系统WIN10报如下错误，本地的其他gulp任务运行正常，这个是什么原因呢？
admin@admin-PC MINGW64 /e/work/electronPrj/nss2
$ electron-windows-inno-installer ./setup.iss --platform win32-x64 --icon ./favicon.ico
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by Qquanwei** [comment]
很抱歉我没有Windows的开发环境，推荐的使用场景为linux/osx 。 不过你可以尝试下面的解决方法:
  gulp-electron 需要你系统环境中有 7z  (https://github.com/mainyaa/gulp-electron#dependency)

另外： 你能推测出是进行到哪一步失败的吗，有没有联网下载electron-win32-x64.zip 这个文件 , 是否显示解压成功了 ？

如果你需要更详细的信息，可以修改gulpfile查看执行状态
