### ISSUE TITLE
Unhandled rejection TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by tanzhihang** [Qquanwei/electron-windows-inno-installer#3]
执行的时候报错，但是能够成功compile成setup.exe。安装后运行也没问题。不知道报错原因在哪

```
[14:32:55] Starting 'version'...
[14:32:55] Finished 'version' after 822 μs
[14:32:55] Starting 'copy:modules'...
[14:32:58] Finished 'copy:modules' after 3.21 s
[14:32:58] Starting 'copy'...
[14:32:58] Finished 'copy' after 8.63 ms
[14:32:58] Starting 'electron'...
[14:32:58] gulp-electron all distribute done.
Unhandled rejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at /Users/joshua/Desktop/electron/demo/node_modules/gulp-electron/index.js:173:24
    at tryCatcher (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/joshua/Desktop/electron/demo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

[14:32:58] Finished 'electron' after 18 ms
[14:32:58] Starting 'inno'...
stderr: fixme:file:SetSearchPathMode (8001): stub
fixme:process:SetProcessDEPPolicy (1): stub

stderr: fixme:file:SetSearchPathMode (8001): stub
fixme:process:SetProcessDEPPolicy (1): stub

stdout: Inno Setup 5 Command-Line Compiler
Copyright (C) 1997-2015 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2015 Martijn Laan
Inno Setup Preprocessor
Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.

stdout:
Compiler engine version: Inno Setup 5.5.6 (a)
```

**Comment by Qquanwei** [comment]
https://github.com/Qquanwei/electron-windows-inno-installer/commit/e7f675fc7e8685cbb315a9c6d53d9410255976a2

升级一下 0.3.26 试一下有没有解决，而且也增加了详细信息的输出

**Comment by tanzhihang** [comment]
原来在 package.json文件里少了name属性，下载zip文件的路径不对所以报错了
