### ISSUE TITLE
error:  required issfile or issfile not exists

### ISSUE THREAD

**Issue by tianxiangbing** [Qquanwei/electron-windows-inno-installer#7]
执行electron-windows-inno-installer mysetup.iss --icon ./favicon.ico --platform win32-x64这个命令报错
error:  required issfile or issfile not exists
环境 是windows，是还要配什么环境变量吗？

**Comment by tianxiangbing** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by Qquanwei** [comment]
你需要创建一个iss文件，并且编辑一下iss文件头。具体请参照下readme
